#file: noinspection YAMLSchemaValidation
name: Unit Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          submodules: recursive
      - name: Set up system dependencies on Linux
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y tree cloc wget curl make zip git-lfs
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt -r requirements-test.txt
      - name: Run unit tests
        env:
          CI: 'true'
          PYTHONPATH: .
        shell: bash
        run: |
          python -m compileall inf test
          make unittest RANGE_DIR=. WORKERS=4
