#file: noinspection YAMLSchemaValidation
name: E621 Squash

on:
  #  push:
  workflow_dispatch:
  schedule:
    - cron: '15 21 * * *'

jobs:
  unittest:
    name: Code Test Newest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.8'

    steps:
      - name: Get system version for Linux
        if: ${{ contains(matrix.os, 'ubuntu') }}
        shell: bash
        run: |
          echo "OS_NAME=Linux" >> $GITHUB_ENV
          echo "IS_WIN=" >> $GITHUB_ENV
          echo "IS_MAC=" >> $GITHUB_ENV
      - name: Set environment for Cpython
        if: ${{ !contains(matrix.python-version, 'pypy') }}
        shell: bash
        run: |
          echo "IS_PYPY=" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 20
          submodules: 'recursive'
      - name: Set up system dependencies on Linux
        if: ${{ env.OS_NAME == 'Linux' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y tree cloc wget curl make zip
          sudo apt-get install -y git-lfs
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade flake8 setuptools wheel twine
          pip install -r requirements.txt
      - name: Test the basic environment
        shell: bash
        run: |
          python -V
          pip --version
          pip list
          tree .
          cloc inf
          cloc test
      - name: Run unittest
        env:
          CI: 'true'
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          REMOTE_REPOSITORY_E621: ${{ secrets.REMOTE_REPOSITORY_E621 }}
          REMOTE_REPOSITORY_E621_PUBLIC: ${{ secrets.REMOTE_REPOSITORY_E621_PUBLIC }}
          REMOTE_REPOSITORY_E621_2024: ${{ secrets.REMOTE_REPOSITORY_E621_2024 }}
          REMOTE_REPOSITORY_E621_PUBLIC_4M: ${{ secrets.REMOTE_REPOSITORY_E621_PUBLIC_4M }}
          REMOTE_REPOSITORY_E621_4M_IDX: ${{ secrets.REMOTE_REPOSITORY_E621_4M_IDX }}
        shell: bash
        run: |
          python -m inf.e621.dbsquash
